# -*- coding: utf-8 -*-
"""Reto 2 Python_David_Bayter

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-yaYKXCgYNKW4ZoKy8f7VcqE1eqq-TgB
"""



"""La empresa company ODS tiene un problema en su departamento de desarrollo, necesitan hacer un programa que le de al usuario un menú donde tenga las opciones de:

1.	Ingresar una fecha, días, mes y año y saber si esa fecha ingresada existe o no existe (tener presente que cuando el año es bisiesto febrero tiene 29 días)
2.	Ingresar un numero y decirle al usuario si ese numero es primo o no
3.	Ingresar un numero e indicarle al usuario de cuantas cifras es; ejemplo: 356 tiene 3 cifras.
4.	La opción de salir del programa 

"""

while True:
    print("\n Bienvenido al programa que le dará solución a sus problemas, eliga la opción que desee realizar: \n\n 1. Ingresar una fecha (d/m/a) y determinar si esta existe \n 2. Determinar si un número es primo o no \n 3. Indicar cuantas cifras contiene un numero entero  \n 0. Salir del programa  \n")
    opc=int(input("Opción de menu a elegir..."))

    if opc==1:
        print("\n""Grandioso, has elegido la opción de determinar si una fecha existe. \n Ahora, te pediré el día (1-31), mes (1-12) y año (ej: 1995) y te diré si la fecha es correcta o no")
        dia=int(input("Ingrese el día: ")) #Los días van de 1 a 31. Pero para determinados meses solo van de 1 a 30. Para febrero(2) van de 1-28, o de 1-29 si es bisiesto. 
        mes=int(input("Ingrese el mes: ")) #Tienen: 31 días enero(1), marzo(3), mayo(5), julio(7), agosto(8), octubre(10) y diciembre(12); 30 días abril(4), junio(6), septiembre(9) y noviembre(11)
        ano=int(input("Ingrese el año: "))
        if ((mes==1 or mes==3 or mes==5 or mes==7 or mes==8 or mes==10 or mes==12) and ((dia>=1) and (dia<=31)) and ano>=0):
            print(f"La fecha {dia}/{mes}/{ano}, es correcta")
        elif ((mes==4 or mes==6 or mes==9 or mes==11) and ((dia>=1) and dia<=30) and ano>=0):
            print(f"La fecha {dia}/{mes}/{ano}, es correcta")
        elif (mes==2 and (((ano %4==0 and ano%100!=0 and ano>=0) or ano%400==0)) and (dia>=1 and dia<=29) ):
            print(f"La fecha {dia}/{mes}/{ano}, es correcta, y además es año bisiesto")
        elif (mes==2 and (dia>=1 and dia<=28) and ano>=0 ):
            print(f"La fecha {dia}/{mes}/{ano}, es correcta")
        else:
            print(f"La fecha {dia}/{mes}/{ano}, es INCORRECTA")
                
    elif opc==2:
        cont=0
        print("\n Genial, acompañame para determinar si tu numero es primo o no")   
        num=int(input("Ingrese el número que desea verficar "))
        if num==0:
            print("0 o cero, no es un número válido")

        for i in range(1,num+1):
            if num % i==0:
                cont=cont+1
            
        if cont==2:
            print(f"El número {num}, es primo \n")
        else:
            print(f"El número {num} NO es primo \n")


    elif opc==3:
        print("Bien hecho, ahora vamos a contar cuantos digitos tiene tu numero entero")
        num=(int(input("Ingresa el número entero que desees")))
        contador=len(str((num)))
        print(f"\n El numero {num} tiene {contador} dígitos")


    elif opc==0:
        break
    
    else:
        print("No es una opción válida, puedes hacerlo mejor ;)")