# -*- coding: utf-8 -*-
"""Reto 3_DavidBayter

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q0eherHnhtSeRW4_QSOugjg3QdW8ecp5
"""

nombres=[] #Como el enunciado lo exige, se almacena cada dato en su respectiva lista
ventas=[] 
comisiones=[]

print("Bienvenido, este es el software de la empresa Hydrasoft desarrollado para llevar registro de sus clientes, sus ventas y sus comisiones")
print("A continuación se le pedirán una serie de datos, y el programa lo irá guiando a través de un menú para atender sus requerimientos")
print("Desarrolado por: David Bayter Copyright_2021 \n\n")

while True:
    try:
        num=int(input("Ingrese el número de vendedores que tuvo la empresa HydraSoft este año "))
        if num >=0:
            x=num+1
            break
        else:
            print("Números negativos no son válidos")
    except ValueError:
        print("Ingrese solo valores numéricos, por favor.")

for i in range(1,x):
    print("\n")
    nombre=input(f"Ingrese el nombre del vendedor No. {i}: ")
    
    while True:
        try:
            venta=float(input(f"Ingrese la venta total anual del vendedor No. {i}: $COP "))
            if venta>=0:
                break
            else:
                print("No se adminten ventas negativas, es imposible. Verifique porfavor.")
        except ValueError:
            print("Solo se admiten valores numéricos. Ej: Digite 1000 NO 'mil' ")

    while True:
        try:
            comision=float(input(f"Ingrese la comisión total ganada por las ventas del vendedor No. {i}: $COP ")) #Aquí haré la verificación del prorrateo de comisión según ventas
            if venta<=1000000 and comision==0:
                break
            elif venta <=3000000 and comision==venta*0.1:
                break
            elif venta<=5000000 and comision==venta*0.2:
                break
            elif venta>5000000 and comision==venta*0.25:
                break
            else:
                print(f"""Comision errada, verifique según las políticas de la empresa
                Si venta 0 - $1.000.000, NO hay comisión 
                Si venta mayor que $1.000.000 hasta $3.000.000, comisión del 10% --- Si fuese el caso su comisión sería $COP {venta*0.1}
                Si venta mayor que $3.000.000 hasta $5.000.000, comisión del 20% --- Si fuese el caso su comisión sería $COP {venta*0.2}
                Si venta mayor que $5.000.000, comisión del 25% --- Si fuese el caso su comisión sería $COP {venta*0.25}
                """)
        except ValueError:
            print("Solo se aceptan valores numéricos")

    nombres.append(nombre)
    ventas.append(venta)
    comisiones.append(comision)

print("Felicitaciones, ya hemos llenado la base de datos con todos tus registros,ahora escoga una opción a realizar del siguiente menú:")

while True:
    print("""
    MENÚ
    1. Conocer el vendedor con el mayor total de ventas en el año, tu vendedor estrella. 
    2. Cononcer el total de ventas en el año y el total de comisiones pagadas
    3. Conocer el vendedor con el menor total de ventas en el año.
    0. Salir del Menú
    """)
    while True:
        try:
            opc=int(input())
            break
        except ValueError:
            print("Escoja una opción válida")

    if opc==1:
        ventamax=max(ventas)
        indmax= ventas.index(ventamax)
        print(f"El vendedor con el mayor total de ventas en el año es {nombres[indmax]}, con un total de ventas de $COP {ventamax} y una comisión total de $COP {comisiones[indmax]} .  ")

    elif opc==2:
        totalventas=sum(ventas)
        totalcomisiones=sum(comisiones)
        print(f"El total del ventas durante el año es de $COP {totalventas} y el total de comisiones pagadas es de $COP {totalcomisiones}")

    elif opc==3:
        ventamin=min(ventas)
        indmin= ventas.index(ventamin)
        print(f"El vendedor con el menor total de ventas en el año es {nombres[indmin]}, con un total de ventas de $COP {ventamin} y una comisión total de $COP {comisiones[indmin]} .  ")

    elif opc==0:
        print("Gracias por usar nuestro software, Adios ")
        break

    else:
        print("Ingrese un valor de Menú correcto")